# Generated by Django 3.0.3 on 2020-03-14 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transactions_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_mobile', models.CharField(max_length=10)),
                ('Recharge_mobile', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=5)),
                ('Status', models.CharField(default='Failed', max_length=15)),
                ('Payment_method', models.CharField(blank=True, max_length=15)),
                ('Date_Time', models.DateTimeField(default=datetime.datetime(2020, 3, 14, 13, 24, 58, 7434))),
            ],
        ),
    ]
