# Generated by Django 3.0.3 on 2020-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200315_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
