# Generated by Django 3.0.3 on 2020-03-15 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200315_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 4, 16, 14, 717109, tzinfo=utc)),
        ),
    ]
