# Generated by Django 3.0.3 on 2020-03-15 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200315_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='email',
            field=models.EmailField(default='devaniurvish881@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2020, 3, 15, 11, 21, 14, 638095, tzinfo=utc), max_length=19),
        ),
    ]
