# Generated by Django 3.0.3 on 2020-03-23 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200315_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator', models.CharField(max_length=15)),
                ('Price', models.IntegerField()),
                ('Talktime', models.IntegerField()),
                ('Benifits', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2020, 3, 23, 4, 12, 32, 916289, tzinfo=utc), max_length=19),
        ),
    ]
