# Generated by Django 3.0.3 on 2020-03-23 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200323_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='Talktime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2020, 3, 23, 4, 23, 9, 716412, tzinfo=utc), max_length=19),
        ),
    ]
